name: gb_latest_version
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  responsive_sizer: ^3.1.1

  #  Generate web view
  flutter_inappwebview: ^5.7.2+3

  #  Whatsapp story path
  saf: ^1.0.3+4
  permission_handler: ^10.2.0
  video_thumbnail: ^0.5.3

  #  play video
  video_player: ^2.6.0

  #  toast message
  fluttertoast: ^8.1.2

  #  country picker
  intl_phone_field: ^3.1.0

  #  url open
  url_launcher: ^6.1.10

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/home_screen/
    - assets/images/onboarding_screen/
    - assets/images/splash_screen/
    - assets/images/drawer/
    - assets/images/direct_chat_screen/
    - assets/images/whats_cleaner_screen/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900

  uses-material-design: true

